### ISSUE TITLE
请问给一下这个项目中的AOI性能对比代码有么

### ISSUE THREAD

**Issue by findstr** [changnet/MServer#2]
我是从这个blog `https://www.cnblogs.com/coding-my-life/p/14256640.html`进来的

**Comment by changnet** [comment]
https://github.com/changnet/MServer/blob/master/server/src/test/grid_aoi_test.lua

https://github.com/changnet/MServer/blob/master/server/src/test/list_aoi_test.lua

**Comment by findstr** [comment]
好的，谢谢
